// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4Q4Q1EmuxWnngjwaciHxJdmNy66_9BA',
    appId: '1:441044772766:web:15020938dc3b48f9d2988f',
    messagingSenderId: '441044772766',
    projectId: 'test-app-f81da',
    authDomain: 'test-app-f81da.firebaseapp.com',
    storageBucket: 'test-app-f81da.appspot.com',
    measurementId: 'G-HVCJSCPD86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4WtWY4jRGXsXMtqzLB3UZHp8f-Ep3w8I',
    appId: '1:441044772766:android:62ce83dcdde758c6d2988f',
    messagingSenderId: '441044772766',
    projectId: 'test-app-f81da',
    storageBucket: 'test-app-f81da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnElsgxLwW_YXFQzaaylvjnIyKBOeosc',
    appId: '1:441044772766:ios:1239826cfc041bc6d2988f',
    messagingSenderId: '441044772766',
    projectId: 'test-app-f81da',
    storageBucket: 'test-app-f81da.appspot.com',
    iosClientId: '441044772766-0f5gn4s980edc43n46pv19v3973sr378.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVnElsgxLwW_YXFQzaaylvjnIyKBOeosc',
    appId: '1:441044772766:ios:1239826cfc041bc6d2988f',
    messagingSenderId: '441044772766',
    projectId: 'test-app-f81da',
    storageBucket: 'test-app-f81da.appspot.com',
    iosClientId: '441044772766-0f5gn4s980edc43n46pv19v3973sr378.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
